<?xml version="1.0" encoding="utf-8"?><Database Name="EscDirectaDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=Pablo\ESCDIRECTASQL;Initial Catalog=EscDirectaDB;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="LINQ2.Properties.Settings" SettingsPropertyName="EscDirectaDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Universidad" Member="Universidad">
    <Type Name="Universidad">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Universidad_Estudiante" Member="Estudiante" ThisKey="Id" OtherKey="UniversidadId" Type="Estudiante" />
    </Type>
  </Table>
  <Table Name="dbo.Estudiante" Member="Estudiante">
    <Type Name="Estudiante">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Genero" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UniversidadId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Estudiante_MateriaEstudiante" Member="MateriaEstudiante" ThisKey="Id" OtherKey="EstudianteId" Type="MateriaEstudiante" />
      <Association Name="Universidad_Estudiante" Member="Universidad" ThisKey="UniversidadId" OtherKey="Id" Type="Universidad" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Materia" Member="Materia">
    <Type Name="Materia">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Materia_MateriaEstudiante" Member="MateriaEstudiante" ThisKey="Id" OtherKey="MateriaId" Type="MateriaEstudiante" />
    </Type>
  </Table>
  <Table Name="dbo.MateriaEstudiante" Member="MateriaEstudiante">
    <Type Name="MateriaEstudiante">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EstudianteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MateriaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Estudiante_MateriaEstudiante" Member="Estudiante" ThisKey="EstudianteId" OtherKey="Id" Type="Estudiante" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Materia_MateriaEstudiante" Member="Materia" ThisKey="MateriaId" OtherKey="Id" Type="Materia" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>